##############################################################################
# 
# Generated by by:  Javi Garcia      19-Aug-2003
# Machine: FOTOPLOTTER T-TECH        NC: T-TECH
# Description
# Fotoploter for PCB's. GERBER format output
#
# Revisiones
# 18-08-2003 # Javi Garcia # Initial
# 15-03-2005 # Javi Garcia # Updated to NX3
#
##############################################################################

#source [MOM_ask_env_var UGII_CAM_DEBUG_DIR]mom_review.tcl; MOM_set_debug_mode ON


set mom_kin_machine_resolution             .001


#  G

set mom_sys_linear_code                    1
set mom_sys_circle_code_CLW                2
set mom_sys_circle_code_CCLW               3

set mom_sys_light_code(ON)                 1
set mom_sys_light_code(OFF)                2
set mom_sys_light_code(DOT)                3
set mom_sys_light_status                   OFF



proc  MOM_start_of_program {} {
   MOM_output_literal "G04 FORMATO 3.3"
   MOM_output_literal "G04 SUPRIMIDOS CERO A LA IZQUIERDA"
   MOM_output_literal "G04 UNIDADES EN MM"
   MOM_output_literal "G75 G90"
}

proc  MOM_end_of_program {} {

   global mom_output_file_full_name
   global mom_output_file_directory
   global mom_group_name
   global mom_sys_light_status

   set mom_sys_light_status OFF
   MOM_do_template Light
   MOM_output_literal "M2"

# Close the file and rename it

   set nombre [string range $mom_group_name 1 8]
   set nombre [format "%04d" $nombre]
   set extension ".nc"

   MOM_close_output_file $mom_output_file_full_name
   set new_file $mom_output_file_directory$nombre$extension
   file rename -force $mom_output_file_full_name  $new_file
}


proc  MOM_initial_move {} {
   global mom_sys_light_status

   set mom_sys_light_status OFF
   MOM_do_template Linear
}

proc  MOM_first_move {} {
   global mom_pos mom_prev_pos
   global mom_sys_light_status

   if {$mom_prev_pos(0) != $mom_pos(0)} {
      set mom_sys_light_status OFF
      MOM_do_template Linear
   } else {
      if  {$mom_prev_pos(1) != $mom_pos(1)} {
         set mom_sys_light_status OFF
         MOM_do_template Linear
      }
   }
}

proc MOM_rapid_move {} {
   global mom_pos mom_prev_pos
   global mom_sys_light_status

   if {$mom_prev_pos(0) != $mom_pos(0)} {
      set mom_sys_light_status OFF
      MOM_do_template Linear
   } else {
      if  {$mom_prev_pos(1) != $mom_pos(1)} {
         set mom_sys_light_status OFF
         MOM_do_template Linear
      }
   }
}

proc MOM_linear_move {} {
   global mom_pos mom_prev_pos
   global mom_sys_light_status

   if {$mom_prev_pos(0) != $mom_pos(0)} {
      set mom_sys_light_status ON
      MOM_do_template Linear
   } else {
      if  {$mom_prev_pos(1) != $mom_pos(1)} {
         set mom_sys_light_status ON
         MOM_do_template Linear
      }
   }
}

proc MOM_circular_move {} {

   global mom_arc_direction
   global mom_arc_angle
   global mom_arc_radius
   global mom_sys_light_status

   set mom_sys_light_status ON

   if {$mom_arc_angle*$mom_arc_radius*3.14/180. < 0.01 } {
      MOM_do_template Linear
   } else {
      if { $mom_arc_direction == "CLW" } { MOM_do_template Circle_CLW}
      if { $mom_arc_direction == "CCLW" } { MOM_do_template Circle_CCLW}
   }
}

proc MOM_first_tool {} {
   global mom_sys_light_status

   set mom_sys_light_status OFF

   MOM_do_template Light
   MOM_do_template Apertura
}

proc MOM_tool_change {} {
   global mom_sys_light_status

   set mom_sys_light_status OFF

   MOM_do_template Light
   MOM_do_template Apertura
}

proc  MOM_drill {} {

   global mom_sys_light_status

   set mom_sys_light_status OFF
   MOM_do_template Light

   MOM_force once X Y

}

proc  MOM_drill_move {} {

   global mom_sys_light_status

   set mom_sys_light_status DOT

   MOM_force once D
   MOM_do_template Linear

   set mom_sys_light_status OFF
}

proc MOM_cycle_off {} { }

proc MOM_spindle_rpm {} { }
proc MOM_start_of_group {} { }
proc MOM_end_of_group {} { }
proc MOM_start_of_path {} { }
proc MOM_end_of_path {} { }
proc MOM_machine_mode {} { }
proc MOM_msys {} { }
proc MOM_set_csys {} { }
proc MOM_before_motion {} { }



proc MOM_catch_warning { } {

  global mom_warning_info

  MOM_output_to_listing_device " * ERROR *"
  MOM_output_to_listing_device "$mom_warning_info"
}

